# Generated by Django 5.2.4 on 2025-07-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comments",
                    models.ManyToManyField(
                        blank=True, related_name="boards", to="comment.comment"
                    ),
                ),
            ],
        ),
    ]
